openapi: 3.0.0
info:
  version: "1.0.0"
  title: stack-overfaux
  description: The API for interacting with StackOverfaux
paths:
  /users:
    get:
      tags:
        - Users
      description: returns all registered users
      responses:
        '200':
          description: List of all users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /users/{name}:
    post:
      tags:
        - Users
      description: Creates new user
      parameters:
        - name: 'name'
          in: path
          required: true
          schema:
            type: 'string'
      responses:
        '201':
          description: successfully registered user
          
    get:
      tags:
        - Users
      description: Gets a user by name
      parameters:
        - name: 'name'
          in: path
          required: true
          schema:
            type: 'string'
      responses:
        '200':
          description: Successfully returned user
          
  /questions:
    get:
      tags:
        - Questions
      description: Gets all questions with optional filtering
      parameters:
        - name: 'id'
          in: query
          required: false
          schema:
            type: integer
          description: Filter by question ID
        - name: 'user'
          in: query
          required: false
          schema:
            type: string
          description: Filter by username
      responses:
        '200':
          description: Successfully returned questions
    post:
      tags:
        - Questions
      description: Create new question
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - body
                - user_name
              properties:
                title:
                  type: string
                body:
                  type: string
                user_name:
                  type: string
      responses:
        '201':
          description: Successfully returned question

  /answers:
    get:
      tags:
        - Questions
      description: Gets all answers with optional filtering
      parameters:
        - name: 'id'
          in: query
          required: false
          schema:
            type: integer
          description: Filter by question ID
        - name: 'user'
          in: query
          required: false
          schema:
            type: string
          description: Filter by username
        - name: 'question'
          in: query
          required: false
          schema:
            type: integer
          description: Filter by question ID
      responses:
        '200':
          description: Successfully returned questions
    post:
      tags:
        - Questions
      description: Create new question
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - body
                - user_name
              properties:
                title:
                  type: string
                body:
                  type: string
                user_name:
                  type: string
      responses:
        '201':
          description: Successfully returned question


  /comments:
    get:
      tags:
        - Questions
      description: Gets all answers with optional filtering
      parameters:
        - name: 'id'
          in: query
          required: false
          schema:
            type: integer
          description: Filter by question ID
        - name: 'user'
          in: query
          required: false
          schema:
            type: string
          description: Filter by username
        - name: 'parent'
          in: query
          required: false
          schema:
            type: integer
          description: Filter by parent ID (question or answer)
      responses:
        '200':
          description: Successfully returned questions
    post:
      tags:
        - Questions
      description: Create new question
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - body
                - user_name
              properties:
                title:
                  type: string
                body:
                  type: string
                user_name:
                  type: string
      responses:
        '201':
          description: Successfully returned question
