version: '3.8'

services:
  db:
    build:
      context: ./db
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin: 
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: your_mail@gmail.com
      PGADMIN_DEFAULT_PASSWORD: your_password
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data: